#===- tools/itoa/Makefile -----------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL := ../..
TOOLNAME := iota
LINK_COMPONENTS := bitreader asmparser irreader

include $(LEVEL)/Makefile.common
